version: 0.2

phases:
  pre_build:
    commands:
      - echo Iniciando sesión en Docker...
  build:
    commands:
      - echo Construyendo la imagen Docker...
      - docker build -t mi-ejercicio-app .
      - echo Ejecutando el contenedor (Simulación)...
      - docker run mi-ejercicio-app
  post_build:
    commands:
      - echo Subiendo el log al bucket de S3...
      - aws s3 cp backup.log s3://actividad3-devops/backup.log

artifacts:
  files:
    - backup.log
    - resultados.json