version: 0.2

phases:
  pre_build:
    commands:
      - echo "Preparando Docker..."
  build:
    commands:
      - echo "Construyendo y ejecutando contenedor..."
      - docker build -t mi-app-ejercicio .
      - docker run --name contenedor-temporal mi-app-ejercicio
  post_build:
    commands:
      - echo "Extrayendo logs del contenedor..."
      - docker cp contenedor-temporal:/app/backup.log .
      - echo "Subiendo log a S3..."
      - aws s3 cp backup.log s3://TU-BUCKET-NOMBRE/backup.log

artifacts:
  files:
    - backup.log
    - resultados.json